### ISSUE TITLE
rewrite统一

### ISSUE THREAD

**Issue by iRuxu** [JX3BOX/world#23]
## 跳转
quest/#/view/23466
跳转至 quest/23466

- [x] 已完成

**Comment by iRuxu** [comment]
## 首页
增加任务模块
<img width="812" alt="image" src="https://user-images.githubusercontent.com/8476969/178121439-43e41ed3-bd88-4c55-ae6a-b4a4beefb26a.png">

- [ ] 已完成

**Comment by iRuxu** [comment]
## 评论问题
<img width="1271" alt="image" src="https://user-images.githubusercontent.com/8476969/178121493-955f87f4-e296-461b-b007-b013047525bd.png">
可能需要改common ui组件？？？

- [ ] 已完成

**Comment by Kaviilee** [comment]
> ## 评论问题
> <img alt="image" width="1271" src="https://user-images.githubusercontent.com/8476969/178121493-955f87f4-e296-461b-b007-b013047525bd.png">
> 
> 可能需要改common ui组件？？？ http://localhost:8081/quest/23466#
> * [ ]  已完成
> 
> ![image](https://user-images.githubusercontent.com/25825282/178137296-6921884a-36ee-49e7-a6b6-fc26a199055c.png) 评论模块是否未添加 quest 类型

胡哥，wiki评论模块是不是需要后台添加类型才能提交成功
![image](https://user-images.githubusercontent.com/25825282/178137566-542b41c1-3b25-46c5-a852-06b1d80442b4.png)
![image](https://user-images.githubusercontent.com/25825282/178137568-937f03a1-bd5f-4b32-a779-4ec981e30939.png)
![image](https://user-images.githubusercontent.com/25825282/178137578-ad46429e-4d0a-4765-9d3e-a881de1fe9b7.png)
